### ISSUE TITLE
monom repo coverage is not working properly

### ISSUE THREAD

**Issue by maxzod** [Flutterando/flutter-coverage#9]
```
OS : win 10`
vs code version : 1.71.2
Flutter Coverage version  : 0.0.4
```

`settings.json`
```json
  "flutter-coverage.coverageFilePaths": ["coverage", "packages/**/coverage"]
```

related to #5 
code to re produce  https://github.com/maxzod/queen
it should group each package coverage by the package

![image](https://user-images.githubusercontent.com/47630729/193996482-d9f540ec-3015-4eb4-9405-cb93509b66db.png)

instead it group them all in single group named after the root directory file name

![image](https://user-images.githubusercontent.com/47630729/193996375-b9cdcd7e-bf1e-4623-9a10-fb2a948fb593.png)

- by clicking on any one of them it cant open the source of the selected file and show this message 

![image](https://user-images.githubusercontent.com/47630729/193996383-9e0184e8-c8ff-4100-803f-de477f2efa43.png)

**Comment by PatrickWulfe** [comment]
I'm fairly certain this is due to the fact that in the coverage files generated by 'flutter test --coverage' use relative file paths.  If you look in the lcov files, each file record starts with 'lib/<rest_of_file_name>'.

I'm currently using a customized version of a dart package called 'combine_coverage' to generate an lcov file for my entire monorepo and have it working with this extension.  In the lcov files generated there, it includes the '/packages/<package_name>/' in the relative file path which fixes both the issues of all tests being grouped into lib in the extension display and the editor not being able to find the file.

I would definitely prefer monorepo support in this extension though so I don't have to run extra commands to get my coverage, but it works for now.  Hope this helps!

**Comment by xeladu** [comment]
Although this issue is rather old, I wanted to add that for me, it works!

![image](https://github.com/Flutterando/flutter-coverage/assets/97696030/435fda8c-1529-451d-a4ff-2b5c2b58b81f)

I have the same extension version and my coverageFilePath setting is identical.

**Comment by maxzod** [comment]
indeed it works now  ,
thanks , @xeladu
